[package]
name = "tradingview-rs"
authors = ["Nguyen Thanh Dat <dat.nguyen@bitbytelab.io>"]
version = "0.3.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/bitbytelabio/tradingview-rs"
readme = "README.md"
description = "Tradingview datafeed api `tradingview-rs` project."
resolver = "3"

[lib]
name = "tradingview"
path = "src/lib.rs"

[[bench]]
harness = false
name = "price_iterable_bench"

[dependencies]
async-trait = "0.1"
base64 = "0.22"
bon = "3"
chrono = { version = "0.4", features = ["serde"] }
dashmap = { version = "6.1.0", features = ["inline", "rayon", "serde"] }
futures-util = {
  version = "0.3",
  default-features = false,
  features = [
    "sink",
    "std",
  ]
}
google-authenticator = { version = "0.4", optional = true }
iso_currency = { version = "0.5", features = ["with-serde"] }
rand = "0.9"
regex = "1"
reqwest = {
  version = "0.13.4",
  default-features = false,
  features = [
    "cookies",
    "json",
    "query",
  ]
}
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = "2"
tokio = { version = "1", default-features = false, features = ["macros", "rt"] }
tokio-tungstenite = { version = "0.29", features = ["url"] }
tokio-util = { version = "0.7", features = ["futures-util", "tracing"] }
tracing = "0.1"
url = "2"
urlencoding = "2"
ustr = { version = "1.1.0", features = ["serde"] }

[dev-dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
colored = "3"
criterion = { version = "0.6", features = ["html_reports"] }
csv = "1"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"

[features]
default = ["rustls-tls", "user"]
native-tls = ["reqwest/native-tls", "tokio-tungstenite/native-tls"]
rustls-tls = ["reqwest/rustls", "tokio-tungstenite/rustls-tls-webpki-roots"]
user = ["dep:google-authenticator"]
