pub mod models;
pub(crate) mod utils;

lazy_static::lazy_static! {
    pub static ref ALL_QUOTE_FIELDS: Vec<&'static str> = vec![
        "lp",
        "lp_time",
        "ask",
        "bid",
        "bid_size",
        "ask_size",
        "ch",
        "chp",
        "volume",
        "high_price",
        "low_price",
        "open_price",
        "prev_close_price",
        "currency_id",
        "current_session",
        "description",
        "exchange",
        "format",
        "fractional",
        "is_tradable",
        "language",
        "local_description",
        "logoid",
        "minmov",
        "minmove2",
        "original_name",
        "pricescale",
        "pro_name",
        "short_name",
        "type",
        "update_mode",
        "fundamentals",
        "rch",
        "rchp",
        "rtc",
        "rtc_time",
        "status",
        "industry",
        "basic_eps_net_income",
        "beta_1_year",
        "market_cap_basic",
        "earnings_per_share_basic_ttm",
        "price_earnings_ttm",
        "sector",
        "dividends_yield",
        "timezone",
        "country",
        "provider_id"
    ];
}
