GET /pine-facade/list?filter=fundamental HTTP/2.0
Host: pine-facade.tradingview.com

HTTP/1.1 301  - Moved Permanently
server: CloudFront
date: Tue, 26 Sep 2023 08:20:31 GMT
content-type: text/html
content-length: 167
connection: close
location: https://pine-facade.tradingview.com/pine-facade/list?filter=fundamental
x-cache: Redirect from cloudfront
via: 1.1 31a016dbd007ced2801c71c9d4c1099a.cloudfront.net (CloudFront)
x-amz-cf-pop: SGN50-P1
x-amz-cf-id: AZ6Kdg4YiglOsHYWxeaPr5suND3nDInzoY51FT5beCJcnLg2b596Mg==
cf-team: 1b722c6d78000091ccb0a83400000001

HTTP/2.0 200  - OK
:status: 200
content-type: text/plain; charset=utf-8
date: Tue, 26 Sep 2023 08:19:15 GMT
cache-control: public, max-age=300
etag: W/"m9QfRmF5Bur8Ngfx+gu+7t1E4uKkssbdeogyO3gDDM6lLeFBooBFScwVIS6I5GRbn99ZDOl5T0XrR0QdbnchIw=="
server: tv
via: 443, 1.1 c6a5e9d6e582c5b5b5d4cc992d25047a.cloudfront.net (CloudFront)
strict-transport-security: max-age=63072000; includeSubDomains; preload
access-control-allow-methods: GET, POST, OPTIONS
access-control-allow-credentials: true
access-control-allow-headers: X-CSRFToken
referrer-policy: origin-when-cross-origin
x-content-type-options: nosniff
content-encoding: gzip
vary: Origin
x-cache: Hit from cloudfront
x-amz-cf-pop: SGN50-P1
x-amz-cf-id: CyITVerQrwzsf0IAF-X8utCVFllHVXD92P-MBSjI-kkf3K9hKMpExA==
age: 76
###
GET /pine-facade/list?filter=standard HTTP/1.1
Host: pine-facade.tradingview.com
###
GET /pine-facade/list?filter=candlestick HTTP/1.1
Host: pine-facade.tradingview.com
###
GET /pine-facade/translate/STD%3BPrice_Oscillator/28.0 HTTP/1.1
Host: pine-facade.tradingview.com
###
GET /pine-facade/list?filter=saved HTTP/1.1
Host: pine-facade.tradingview.com
Cookie: sessionid={{$dotenv TV_SESSION}}; sessionid_sign={{$dotenv TV_SIGNATURE}}; device_t={{$dotenv TV_DEVICE_ID}};
###
GET /pine-facade/translate/USER%3B7a78efc35a354d5b8b2e7dc1833524fc/1.0 HTTP/1.1
Host: pine-facade.tradingview.com
Cookie: sessionid={{$dotenv TV_SESSION}}; sessionid_sign={{$dotenv TV_SIGNATURE}}; device_t={{$dotenv TV_DEVICE_ID}};